Repository jenkins-x/exposecontroller, pull requests merged in 2019-04, with the labels that each got.

#176 Add resource limits to job
  charts/exposecontroller/templates/job.yaml
Labels: approved, ok-to-test, size/XS

#180 switch to tekton based pipelines
  .updatebot.yml
  Makefile
  charts/exposecontroller/Makefile
  charts/exposecontroller/values.yaml
  controller/controller.go
  jenkins-x.yml
  scripts/update-bot.sh
Labels: approved, size/L

#178 feat(tls): introduce tls-secret-name to enable manual TLS
  README.md
  charts/exposecontroller/templates/configmap.yaml
  controller/config.go
  controller/controller.go
  exposestrategy/ambassador.go
  exposestrategy/auto.go
  exposestrategy/ingress.go
  exposestrategy/strategy.go
Labels: approved
