Repository jenkins-x/exposecontroller, pull requests merged in 2019-02, with the labels that each got.

#166 Minor grammar correction.
  README.md
Labels: needs-ok-to-test, size/XS

#169 Add ambassador as an exposer
  exposestrategy/ambassador.go
  exposestrategy/strategy.go
Labels: approved, lgtm, ok-to-test, size/L

#168 feature: Added ingress-class option
  charts/exposecontroller/templates/configmap.yaml
  controller/config.go
  controller/controller.go
  exposestrategy/auto.go
  exposestrategy/ingress.go
  exposestrategy/strategy.go
Labels: approved, ok-to-test, size/M

#170 fix up error handling
  exposestrategy/ambassador.go
Labels: approved, size/XS

#174 Add namespace to mapping name to prevent conflicts
  exposestrategy/ambassador.go
Labels: approved, ok-to-test, size/XS

#172 Makefile improvements
  .dockerignore
  Makefile
Labels: approved, lgtm, size/S
