Repository jenkins-x/exposecontroller, pull requests merged in 2019-01, with the labels that each got.

#162 fix: lets default to looking in the dev namespace for ConfigMaps
  exposecontroller.go
Labels: approved, size/M

#163 fix: fix up possible core dump when loading ConfigMaps
  exposecontroller.go
  exposestrategy/ingress.go
Labels: approved, size/S

#164 fix: work around the exposecontroller pod cannot access Namespaces
  exposecontroller.go
Labels: approved, size/XS

#165 istio-proxy prevents job pods from completing if istio is enabled
  charts/exposecontroller/templates/job.yaml
  exposecontroller.go
Labels: approved, ok-to-test, size/S

#167 fix: Append existing backend paths
  exposestrategy/ingress.go
Labels: approved, ok-to-test, size/XS
