Repository jenkins-x/exposecontroller, pull requests merged in 2019-11, with the labels that each got.

#189 chore: added precommit configuration
  .pre-commit-config.yaml
Labels: approved, lgtm, size/XS

#196 feat: add annotation to specify hostName
  README.md
  exposestrategy/ambassador.go
  exposestrategy/ingress.go
Labels: approved, lgtm, ok-to-test, size/S

#186 feat: Add tls wildcard support
  charts/exposecontroller/templates/configmap.yaml
  controller/config.go
  controller/controller.go
  exposestrategy/auto.go
  exposestrategy/ingress.go
  exposestrategy/strategy.go
Labels: approved, lgtm, lifecycle/stale, lifecycle/stale, ok-to-test, size/M

#185 Update role.yaml
  charts/exposecontroller/templates/role.yaml
Labels: approved, lgtm, lifecycle/stale, lifecycle/stale, ok-to-test, size/XS
